# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

---------------------------------------------------------------------


#### Assignment 1: Array Creation and Manipulation
1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [ ]:
import numpy as np

#task-1
array = np.random.randint(1, 21, size=(5, 5))
print("Orginal Array:")
print(array)

array[:,2] = 1
print("Modified Array:")
print(array)

Orginal Array:
[[ 6  4  6 12  3]
 [14 18 13  9 15]
 [14  4  5  9 10]
 [18 15  9 15 16]
 [20  1  2 14  7]]
Modified Array:
[[ 6  4  1 12  3]
 [14 18  1  9 15]
 [14  4  1  9 10]
 [18 15  1 15 16]
 [20  1  1 14  7]]


In [25]:
#task - 2
array = np.arange(1,17).reshape(4,4)
print("Orginal Array:")
print(array)

np.fill_diagonal(array, 0)
print("Modified Array:")
print(array)

Orginal Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


#### Assignment 2: Array Indexing and Slicing
1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [27]:
#Task 1
array = np.arange(1,37).reshape(6,6)
print("Orginal Array:")
print(array)

sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Orginal Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [28]:
#Task 2
array = np.random.randint(1, 100, size=(5,5))
print("Orginal Array:")
print(array)

border_elements = np.concatenate(
    (array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1])
)
print("Border_elements:")
print(border_elements)

Orginal Array:
[[56 13 31 67 22]
 [99 32 34 43 91]
 [91 30 82 39 77]
 [89 60 46 21 15]
 [71 70 67  6 29]]
Border_elements:
[56 13 31 67 22 71 70 67  6 29 99 91 89 91 77 15]



#### Assignment 3: Array Operations
1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [34]:
#Task 1
array1 = np.random.randint(1, 9, size=(3,4))
array2 = np.random.randint(1, 9, size=(3,4))
print("Array 1:")
print(array1)
print("Array 1:")
print(array2)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element wise addition:")
print(addition)
print("Element wise subtraction:")
print(subtraction)
print("Element wise multiplication:")
print(multiplication)
print("Element wise division:")
print(division)


Array 1:
[[3 5 3 4]
 [1 1 5 4]
 [2 4 6 2]]
Array 1:
[[1 5 4 1]
 [8 7 1 7]
 [7 4 4 4]]
Element wise addition:
[[ 4 10  7  5]
 [ 9  8  6 11]
 [ 9  8 10  6]]
Element wise subtraction:
[[ 2  0 -1  3]
 [-7 -6  4 -3]
 [-5  0  2 -2]]
Element wise multiplication:
[[ 3 25 12  4]
 [ 8  7  5 28]
 [14 16 24  8]]
Element wise division:
[[3.         1.         0.75       4.        ]
 [0.125      0.14285714 5.         0.57142857]
 [0.28571429 1.         1.5        0.5       ]]


In [36]:
#task 2
array = np.arange(1, 17).reshape(4, 4)
print("Orginal Array:")
print(array)

row_sum = np.sum(array, axis=1)
col_sum = np.sum(array, axis=0)

print(f"Row wise sum: {row_sum}")
print(f"Column wise sum: {col_sum}")

Orginal Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise sum: [10 26 42 58]
Column wise sum: [28 32 36 40]
