# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

---------------------------------------------------------------------


#### Assignment 1: Array Creation and Manipulation
1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [2]:
import numpy as np

#task-1
array = np.random.randint(1, 21, size=(5, 5))
print("Orginal Array:")
print(array)

array[:,2] = 1
print("Modified Array:")
print(array)

Orginal Array:
[[18 18  2 19 16]
 [19  4  6 17  6]
 [ 5  1 10  4  5]
 [17 15 10 19  9]
 [16 20  5 18 19]]
Modified Array:
[[18 18  1 19 16]
 [19  4  1 17  6]
 [ 5  1  1  4  5]
 [17 15  1 19  9]
 [16 20  1 18 19]]


In [3]:
#task - 2
array = np.arange(1,17).reshape(4,4)
print("Orginal Array:")
print(array)

np.fill_diagonal(array, 0)
print("Modified Array:")
print(array)

Orginal Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


#### Assignment 2: Array Indexing and Slicing
1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [4]:
#Task 1
array = np.arange(1,37).reshape(6,6)
print("Orginal Array:")
print(array)

sub_array = array[2:5, 1:4]
print("Sub-array:")
print(sub_array)

Orginal Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [5]:
#Task 2
array = np.random.randint(1, 100, size=(5,5))
print("Orginal Array:")
print(array)

border_elements = np.concatenate(
    (array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1])
)
print("Border_elements:")
print(border_elements)

Orginal Array:
[[79 19 72 90 13]
 [50 66 38 67 49]
 [77 62  4 75 49]
 [60 81 47 59 38]
 [65  9 92 49 17]]
Border_elements:
[79 19 72 90 13 65  9 92 49 17 50 77 60 49 49 38]



#### Assignment 3: Array Operations
1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [6]:
#Task 1
array1 = np.random.randint(1, 9, size=(3,4))
array2 = np.random.randint(1, 9, size=(3,4))
print("Array 1:")
print(array1)
print("Array 1:")
print(array2)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element wise addition:")
print(addition)
print("Element wise subtraction:")
print(subtraction)
print("Element wise multiplication:")
print(multiplication)
print("Element wise division:")
print(division)


Array 1:
[[2 4 5 2]
 [3 6 5 1]
 [7 1 8 5]]
Array 1:
[[1 4 5 5]
 [3 1 6 2]
 [2 4 6 2]]
Element wise addition:
[[ 3  8 10  7]
 [ 6  7 11  3]
 [ 9  5 14  7]]
Element wise subtraction:
[[ 1  0  0 -3]
 [ 0  5 -1 -1]
 [ 5 -3  2  3]]
Element wise multiplication:
[[ 2 16 25 10]
 [ 9  6 30  2]
 [14  4 48 10]]
Element wise division:
[[2.         1.         1.         0.4       ]
 [1.         6.         0.83333333 0.5       ]
 [3.5        0.25       1.33333333 2.5       ]]


In [7]:
#task 2
array = np.arange(1, 17).reshape(4, 4)
print("Orginal Array:")
print(array)

row_sum = np.sum(array, axis=1)
col_sum = np.sum(array, axis=0)

print(f"Row wise sum: {row_sum}")
print(f"Column wise sum: {col_sum}")

Orginal Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise sum: [10 26 42 58]
Column wise sum: [28 32 36 40]


#### Assignment 4: Statistical Operations
1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
#task 1
array = np.random.randint(1, 9, size=(5,5))
print("Orginal Array:")
print(array)

mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Orginal Array:
[[8 7 4 4 5]
 [7 7 6 4 1]
 [5 6 3 8 1]
 [6 5 7 3 3]
 [1 8 3 7 7]]
Mean: 5.04
Median: 5.0
Standard Deviation: 2.199636333578803
Variance: 4.838399999999999


In [14]:
#task 2
array = np.arange(1,10).reshape(3,3)
print("Orginal Array:")
print(array)

mean = np.mean(array)
std_dev = np.std(array)
normalizeed_array = (array - mean) / std_dev

print("Normalized array:")
print(normalizeed_array)

Orginal Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


#### Assignment 5: Broadcasting
1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [17]:
#Task 1
array = np.random.randint(1, 9, size=(3,3))
print("Orginal Array:")
print(array)

row_array = np.random.randint(1, 9, size=(3,))
print("Row Array:", row_array)

print("Result array:")
print(array + row_array)

Orginal Array:
[[8 6 8]
 [8 1 1]
 [2 4 5]]
Row Array: [2 7 1]
Result array:
[[10 13  9]
 [10  8  2]
 [ 4 11  6]]


In [23]:
#Task 1
array = np.random.randint(1, 9, size=(4,4))
print("Orginal Array:")
print(array)

col_array = np.random.randint(1, 9, size=(4,))
print("Row Array:", col_array)

print("Result array:")
print(array - col_array[:,np.newaxis])

Orginal Array:
[[1 1 6 2]
 [4 1 3 5]
 [8 7 7 4]
 [3 3 6 1]]
Row Array: [4 8 8 1]
Result array:
[[-3 -3  2 -2]
 [-4 -7 -5 -3]
 [ 0 -1 -1 -4]
 [ 2  2  5  0]]


#### Assignment 6: Linear Algebra
1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [28]:
#Task 1
matrix = np.random.randint(1, 9, size=(3,3))
print("Orginal Matrix:")
print(matrix)

determinant = np.linalg.det(matrix)
print(f"Determinant: {determinant}")

inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

eigenvalues = np.linalg.eigvals(matrix)
print(f"Eigenvalues: {eigenvalues}")

Orginal Matrix:
[[7 5 5]
 [2 1 3]
 [8 7 8]]
Determinant: -20.99999999999999
Inverse:
[[ 0.61904762  0.23809524 -0.47619048]
 [-0.38095238 -0.76190476  0.52380952]
 [-0.28571429  0.42857143  0.14285714]]
Eigenvalues: [15.91711218  1.19081435 -1.10792652]


In [30]:
#Task 2
matrix1 = np.random.randint(1, 9, size=(2,3))
matrix2 = np.random.randint(1, 9, size=(3,2))
print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)

result = np.dot(matrix1, matrix2)
print("Matrix multiplication result:")
print(result)

Matrix 1:
[[3 3 2]
 [7 8 3]]
Matrix 2:
[[7 1]
 [5 4]
 [4 5]]
Matrix multiplication result:
[[ 44  25]
 [101  54]]


#### Assignment 7: Advanced Array Manipulation
1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [35]:
array = np.arange(1, 10).reshape(3,3)
print("Original array:")
print(array)

reshaped_array_1 = array.reshape(1, 9)
print("Reshaped array (1, 9):")
print(reshaped_array_1)

reshaped_array_1 = array.reshape(9, 1)
print("Reshaped array (1, 9):")
print(reshaped_array_1)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (1, 9):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [39]:
#task 2
array = np.random.randint(0, 100, size=(5,5))
print("Orginal Array:")
print(array)

flattened_array = array.flatten()
print(f"Flattened Array: \n{flattened_array}")

reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Orginal Array:
[[24 12 73 40 35]
 [38 73 53 26 81]
 [99 57 11 84 20]
 [75 14 65 96 94]
 [88 15 29  0 28]]
Flattened Array: 
[24 12 73 40 35 38 73 53 26 81 99 57 11 84 20 75 14 65 96 94 88 15 29  0
 28]
Reshaped array:
[[24 12 73 40 35]
 [38 73 53 26 81]
 [99 57 11 84 20]
 [75 14 65 96 94]
 [88 15 29  0 28]]


#### Assignment 8: Fancy Indexing and Boolean Indexing
1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [49]:
#Task 1
array = np.random.randint(0, 9, size=(5,5))
print("Orginal Array:")
print(array)

corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Orginal Array:
[[7 7 4 7 1]
 [4 5 5 7 7]
 [6 5 0 5 4]
 [6 4 2 4 3]
 [6 3 3 1 7]]
Corner elements:
[7 1 6 7]


In [53]:
#Task 2
array = np.random.randint(1, 20, size=(4,4))
print("Orginal Array:")
print(array)

array[array > 10] = 10
print("Modified Array:")
print(array)


Orginal Array:
[[ 8 17  3 18]
 [16 12  4  4]
 [ 6  1  8 14]
 [17 13 11 14]]
Modified Array:
[[ 8 10  3 10]
 [10 10  4  4]
 [ 6  1  8 10]
 [10 10 10 10]]


#### Assignment 9: Structured Arrays
1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [56]:
#task 1
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [59]:
#task 2
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


#### Assignment 10: Masked Arrays
1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [65]:
#Task 1
import numpy.ma as ma
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 2  3 10  3]
 [20 16 20 12]
 [18 15 14 13]
 [18  8 11  1]]
Masked array:
[[2 3 10 3]
 [-- -- -- --]
 [-- -- -- --]
 [-- 8 -- 1]]
Sum of unmasked elements: 27


In [68]:
#Task 2
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 6  8 12]
 [13 13 14]
 [14  4 18]]
Masked array:
[[-- 8 12]
 [13 -- 14]
 [14 4 --]]
Modified masked array:
[[10  8 12]
 [13 10 14]
 [14  4 10]]
