## Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

#create array using numpy
## create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [13]:
arr3 = np.array([[1,2,3,5,4,6]])
print(arr3)

[[1 2 3 5 4 6]]


In [18]:
arr4 = np.array([[1,2,3,5,4,6], [2,3,4,5,5,7], [4,8,7,8,9,0]])
print(arr4)
print(arr4.shape)

[[1 2 3 5 4 6]
 [2 3 4 5 5 7]
 [4 8 7 8 9 0]]
(3, 6)


In [21]:
np.arange(0, 10, 1).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [30]:
## numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10, 20, 30, 40, 50])

#element wise addition
print("Addition:", arr1 + arr2)

#element wise substraction
print("Substraction:", arr1 - arr2)

#element wise multiplication
print("Multiplication:", arr1 * arr2)

#element wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## universal function
arr = np.array([2,3,4,5,6,7])

#sqrt
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#sin
print(np.sin(arr))

#log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131]
[   7.3890561    20.08553692   54.59815003  148.4131591   403.42879349
 1096.63315843]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015]


In [40]:
#array slicing operation and indexing
arr = np.array([[1,2,3,4,5], [5,6,7,8,9], [10,11,12,13,14]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
arr[0,0] #0th row, 0th column

np.int64(1)

In [48]:
arr[1:, 3:]

array([[ 8,  9],
       [13, 14]])

In [56]:
arr[0:2, 2:4]

array([[3, 4],
       [7, 8]])

In [57]:
#modify array elements
arr[0,0] = 100
arr

array([[100,   2,   3,   4,   5],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [58]:
arr[1:] = 100
arr

array([[100,   2,   3,   4,   5],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [62]:
''' 
statistical concepts - normalization
to have a mean of 0 and SD of 1
'''
#initialize a 1d array
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data)

#calculate the mean and standard deviation
mean = np.mean(data)
sd = np.std(data)
print(f"Mean: {mean}\nStandard Deviation: {sd}")

#Normalize the data
normalized_data = (data - mean) / sd
print(f"Normalized data: {normalized_data}")

[ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Standard Deviation: 2.8722813232690143
Normalized data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [67]:
#initialize a 1d array
data = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:", data)

print("Mean: ", np.mean(data))
print("Median: ", np.median(data))
print("Standard Deviation: ", np.std(data))
print("Variance: ", np.var(data))

Array: [ 1  2  3  4  5  6  7  8  9 10]
Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [71]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])